title: Michael Nordmeyer
author:
  name: Michael Nordmeyer
#  email: xxx@example.com
  uri: https://michaelnordmeyer.com/
github_username: michaelnordmeyer
twitter_username: mnordmeyer
linkedin_username: michaelnordmeyer
xing_username: Michael_Nordmeyer
#rss: RSS Feed
description: "Agile Project Management & Software Engineering"
bio: "Freelance software developer, project manager, consultant. Whatever role fits. Likes Ruby on Rails and JavaScript, tolerates Java. Uses HTML/CSS to make the web a better place. Green tea drinker, but Sencha only. üçµ"

show_excerpts: true
 
# https://docs.github.com/en/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-using-jekyll#customizing-your-themes-css
# https://github.com/jekyll/minima#customizing-templates
#theme: minima
remote_theme: michaelnordmeyer/minima
minima:
  date_format: "%Y-%m-%d"
  # social_links:
  #   github: michaelnordmeyer
  #   twitter: mnordmeyer
  #   linkedin: michaelnordmeyer
  #   xing: Michael_Nordmeyer

header_pages:
  - about.md

# https://pages.github.com/versions/
# https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins
plugins:
  - jekyll-redirect-from
#  - jekyll-feed
#  - jekyll-seo-tag
#  - jekyll-sitemap
#  - jekyll-avatar
#  - jemoji
#  - jekyll-mentions
#  - jekyll-include-cache

lang: en
feed:
  path: /feed

## jekyll-seo-tag
title_separator: " ‚Ä¢ "
social:
  name: Michael Nordmeyer
  links:
    - https://twitter.com/mnordmeyer
    - https://www.facebook.com/michaelnordmeyer
    - https://www.linkedin.com/in/michaelnordmeyer
    - https://github.com/michaelnordmeyer
#    - https://www.xing.com/profile/Michael_Nordmeyer
twitter:
  username: mnordmeyer
# logo: /assets/your-company-logo.png

## Analytics
stats:
  no-javascript-url: "https://s.michaelnordmeyer.com"
#  script-url: "https://s.michaelnordmeyer.com/s.js"
  script-url: "https://s.michaelnordmeyer.com/s.min.js"

# defaults:
#   -
#     scope:
#       path: ""
#       type: posts # posts, pages, drafts
#     values:
#       layout: default
#       author: Michael Nordmeyer
#   -
#     scope:
#       path: "projects"
#       type: "pages"
#     values:
#       layout: "project"
#       author: "Mr. Hyde"
